-- Seed migration intentionally left empty.
--
-- Runtime bootstrap now creates the owner from OWNER_EMAIL / OWNER_PASSWORD
-- and seeds services from src/lib/init/services.json when the services table is empty.
-- Barbers and receptionists should be added from the owner's dashboard.
